const EG_STOP=new Set('i you he she it we they a an the and or but to of in on at for from with is am are was were be been being do does did have has had can could would should will may might my your his her our their this that these those as so than then when while if because about into more most very still just really'.split(' '));
const EG_SYN=[['goal','aim','objective','target'],['speak','talk','communicate','express'],['clearly','clear','understandably'],['improve','develop','build','strengthen'],['work','job','career','professional'],['study','learn','learning','school','university','academic'],['difficult','hard','challenging'],['understand','comprehend','follow'],['answer','respond','reply'],['important','essential','useful','valuable'],['confident','confidence','comfortably'],['explain','describe','express'],['idea','ideas','point','points','meaning'],['technology','ai','automation','tools'],['child','children','son','kid','kids'],['money','finance','financial','investment','investing'],['evidence','data','research'],['reason','because','why'],['example','instance']];
let egRec=null,egKind='',egStarted=0,egLast=null;
function egWords(s){return norm(s).split(' ').filter(Boolean)}
function egStem(w){return w.replace(/(ing|ed|ly|es|s)$/,'')}
function egCanon(w){w=egStem(w);for(const g of EG_SYN)if(g.some(x=>egStem(x)===w))return egStem(g[0]);return w}
function egContent(s){return egWords(s).filter(w=>w.length>2&&!EG_STOP.has(w)).map(egCanon)}
function egClamp(x){return Math.max(0,Math.min(100,Math.round(x)))}
function egCoverage(user,target){let t=[...new Set(egContent(target))],u=new Set(egContent(user));let hit=t.filter(x=>u.has(x)),miss=t.filter(x=>!u.has(x));return {score:egClamp(hit.length/Math.max(t.length,1)*100),miss}}
function egSignals(text){let w=egWords(text),lower=' '+norm(text)+' ',con=['because','so','but','although','however','for example','for instance','therefore','while','when','if','which','that'];let filler=w.filter(x=>['um','uh','like','actually','basically','well'].includes(x)).length;return {n:w.length,u:new Set(w).size,c:con.filter(x=>lower.includes(' '+x+' ')).length,f:filler,verb:/\b(am|is|are|was|were|be|have|has|had|do|does|did|can|could|would|should|will|want|need|think|feel|use|make|take|go|work|study|learn|speak|talk|explain|understand|help|improve|develop|get|know|try|like)\b/i.test(text)}}
function egSpeechSupported(){return !!(window.SpeechRecognition||window.webkitSpeechRecognition)}
function egButtons(kind){return `<div class="row" style="justify-content:center"><button class="primary" onclick="egStart('${kind}')">🎙️ 開始說</button><button onclick="egStop()">⏹ 停止＋評分</button></div><p class="small">${egSpeechSupported()?'語音由瀏覽器轉成文字；部分瀏覽器可能使用其線上語音服務。English Gym 不上傳或保存原始錄音。':'此瀏覽器不支援自動轉文字，可在下方自行輸入剛才說的內容再評分。'}</p><textarea id="egSpeechText" placeholder="你的口說轉錄會出現在這裡；也可自行輸入"></textarea><div id="egFeedback"></div><div class="row" style="justify-content:center"><button onclick="egScore('${kind}')">評分我輸入/轉錄的口說</button></div>`}
const egOldRender=render;
render=function(){if(stage!==3&&stage!==4){egOldRender();return}dash();let a=$('area'),next=$('nextBtn');$('startBtn').classList.add('hidden');next.classList.add('hidden');next.textContent='下一步';if(stage===3){$('stage').textContent='3/4 重述＋回饋';a.innerHTML=`<div class="stepTitle">先遮住原句，再自己重述</div><h2>Retrieval Speaking</h2><p>用自己的英文說出同一個意思，不要逐字背原句。</p>${egButtons('retrieval')}`}else{let target=mode===5?20:mode===15?45:75;$('stage').textContent='4/4 自由口說＋回饋';a.innerHTML=`<div class="stepTitle">把英文用在自己身上</div><h2>Free Speaking</h2><p><b>How does this sentence relate to your life or your goals?</b></p><p class="small">目標約 ${target} 秒。用 Point → Reason → Example → Link 說一小段。</p>${egButtons('free')}`}}
function egStart(kind){egKind=kind;egStarted=Date.now();let box=$('egSpeechText');if(box)box.value='';if(!egSpeechSupported()){box?.focus();return}const R=window.SpeechRecognition||window.webkitSpeechRecognition;egRec=new R();egRec.lang='en-US';egRec.interimResults=true;egRec.continuous=true;egRec.onresult=e=>{let s='';for(let i=0;i<e.results.length;i++)s+=e.results[i][0].transcript+' ';if(box)box.value=s.trim()};egRec.onerror=e=>{let f=$('egFeedback');if(f)f.innerHTML=`<div class="error">語音辨識沒有成功（${esc(e.error)}）。可以直接輸入剛才說的內容再評分。</div>`};egRec.onend=()=>{if(egStarted)egScore(egKind)};try{egRec.start()}catch{}}
function egStop(){if(egRec){let r=egRec;egRec=null;try{r.stop()}catch{}}else egScore(egKind||'retrieval')}
function egRetrieval(text,secs){let cov=egCoverage(text,cur.t),copy=similarity(text,cur.t),s=egSignals(text);let meaning=cov.score,reform=copy>=92?45:copy>=80?65:copy>=55?88:copy>=35?78:Math.min(70,meaning),clarity=egClamp((s.verb?45:20)+Math.min(35,s.n*3)+Math.min(20,s.c*10)),overall=egClamp(meaning*.55+reform*.2+clarity*.25),issues=[];if(meaning<70)issues.push('意思有漏掉');if(copy>=90)issues.push('太接近背原句，改用自己的字');if(clarity<65)issues.push('句子太短或結構不完整');if(!issues.length)issues.push('意思完整，下一步練更自然的改述');return {kind:'retrieval',overall,meaning,reform,clarity,miss:cov.miss.slice(0,4),issues,secs}}
function egFree(text,secs){let s=egSignals(text),wpm=secs>2?s.n/(secs/60):0,flu=egClamp((wpm>=70&&wpm<=170?85:wpm>=50?70:45)-(s.n?s.f/s.n:0)*120),structure=egClamp(30+Math.min(35,s.c*15)+Math.min(35,Math.floor(s.n/8)*8)),variety=egClamp(35+(s.n?s.u/s.n*50:0)+Math.min(15,s.c*5)),overall=egClamp(flu*.35+structure*.4+variety*.25),issues=[];if(s.n<18)issues.push('內容太短：補一個 reason 或 example');if(s.c<1)issues.push('加連接詞：because / for example / however');if(s.n&&s.f/s.n>.08)issues.push('贅詞偏多：停頓比 um/uh 更好');if(!issues.length)issues.push('結構已清楚，下一次加更具體的例子');return {kind:'free',overall,fluency:flu,structure,variety,wpm:Math.round(wpm),wordCount:s.n,issues,secs}}
function egScore(kind){let box=$('egSpeechText');if(!box)return;let text=box.value.trim(),out=$('egFeedback');if(!text){out.innerHTML='<div class="error">還沒有文字可以評分。請先說，或輸入剛才說的內容。</div>';return}let secs=egStarted?Math.max(1,Math.round((Date.now()-egStarted)/1000)):Math.max(5,Math.round(egWords(text).length/2));egStarted=0;if(egRec){try{egRec.abort()}catch{}egRec=null}let f=kind==='free'?egFree(text,secs):egRetrieval(text,secs);egLast={...f,text};if(!st.speakingScores)st.speakingScores=[];if(!st.speakingTags)st.speakingTags={};st.speakingScores.push({date:new Date().toISOString(),kind:f.kind,overall:f.overall});if(st.speakingScores.length>100)st.speakingScores=st.speakingScores.slice(-100);for(const tag of f.issues.slice(0,2))st.speakingTags[tag]=(st.speakingTags[tag]||0)+1;save();egRenderFeedback(f,text)}
function egBadge(label,n){return `<div class="metric"><span class="small">${label}</span><b>${n}</b><span class="small">/100</span></div>`}
function egRenderFeedback(f,text){let m=f.kind==='retrieval'?egBadge('意思完整',f.meaning)+egBadge('真正改述',f.reform)+egBadge('句子清晰',f.clarity):egBadge('流暢度',f.fluency)+egBadge('結構',f.structure)+egBadge('詞彙變化',f.variety);let d=f.kind==='retrieval'?`${f.miss.length?`<p><b>你可能漏掉：</b> ${f.miss.map(esc).join(' / ')}</p>`:'<p><b>意思：</b>核心內容有帶到。</p>'}<p><b>可靠參考版本：</b> ${esc(cur.t)}</p>`:`<p><b>這次：</b>${f.wordCount} 字，約 ${f.wpm} words/min。</p><p><b>第二次套這個框架：</b> Point → because… → for example… → so…</p>`;let p=egPrompt(f,text);$('egFeedback').innerHTML=`<div class="tip" style="margin-top:12px;text-align:left"><h3 style="margin-top:0">口說回饋：${f.overall}/100</h3><div class="row">${m}</div><p><b>下一次只改一件事：</b> ${esc(f.issues[0])}</p>${d}<details><summary>為什麼不是「文法100分」？</summary><p class="small">零成本瀏覽器版可以做轉錄、內容覆蓋與流暢/結構指標，但不假裝能像真人或大型語言模型一樣精準判斷所有文法與自然度。</p></details><div class="row"><button class="primary" onclick="egRetry('${f.kind}')">🔁 依回饋再說一次</button><button onclick="egCopyDeep()">🧠 複製給 ChatGPT 深度批改</button></div><textarea id="egDeepPrompt" class="hidden">${esc(p)}</textarea></div>`;$('nextBtn').classList.remove('hidden');$('nextBtn').textContent=f.overall<80?'先跳過，下一步':'下一步'}
function egRetry(kind){let b=$('egSpeechText');if(b)b.value='';$('egFeedback').innerHTML='<div class="tip"><b>第二次：</b>只修剛才那一件事，再說一次。</div>';egStarted=0;setTimeout(()=>egStart(kind),250)}
function egPrompt(f,text){return `你是我的英文口說教練。我的 Speaking 約 A2，目標 C1/UNIGE。\n任務：${f.kind==='retrieval'?'重述同一意思':'自由口說'}\n參考句：${cur.t}\n我的口說轉錄：${text}\n請輸出：1) CEFR 粗估（只評本次） 2) 意思/文法/自然度/邏輯各0-100並解釋 3) 最重要1-2個錯誤 4) Minimal correction 5) Natural version 6) C1 upgrade但不要故意艱深 7) 20-40秒retry任務。不要只稱讚，也不要一次糾正超過2個重點。`}
async function egCopyDeep(){let t=$('egDeepPrompt')?.value||'';try{await navigator.clipboard.writeText(t);alert('已複製。貼到 ChatGPT 就能做深度文法與自然度批改；沒有呼叫付費 API。')}catch{prompt('複製下面文字到 ChatGPT：',t)}}
const egOldNext=nextStage;
nextStage=async function(){if(stage===4&&egLast){if(!st.history)st.history=[];}await egOldNext()}
