/* English Gym v1.5 — IELTS Academic progressive track.
   Original IELTS-style practice created for this app; not official IELTS questions.
   No paid API. Objective items are scored locally; Writing/Speaking use honest practice signals + optional copy-to-ChatGPT review. */
const IELTS_STAGE_NAMES=['','基礎輸出','題型＋時間感','Band 7 橋接','7.5–8 目標訓練'];
const IELTS_SKILL_NAMES={listening:'Listening',reading:'Reading',writing:'Writing',speaking:'Speaking'};
const IELTS_ICON={listening:'🎧',reading:'📚',writing:'✍️',speaking:'🗣️'};

const IELTS_LISTENING=[
 {id:'il-l2-01',stage:2,title:'Library membership enquiry',accent:'en-GB',script:`Good morning. I am calling about joining the university library as a community member. I live nearby but I am not a student. I was told that local residents can apply if they bring a photo ID and proof of address. The annual fee is forty-eight francs, and it allows members to borrow up to six books at a time. Applications are processed at the main information desk from Monday to Friday, between nine in the morning and five in the afternoon. The desk closes for lunch from twelve thirty until one thirty. I would like to come on Thursday after I collect my son from school, so I expect to arrive at about four fifteen.`,q:[
   {type:'text',prompt:'Annual membership fee: ____ francs',answer:['48','forty-eight','forty eight'],explain:'The speaker says the annual fee is forty-eight francs.'},
   {type:'choice',prompt:'How many books may a community member borrow at one time?',options:['4','6','8'],answer:'6',explain:'Members may borrow up to six books.'},
   {type:'choice',prompt:'When is the information desk closed?',options:['12:00–13:00','12:30–13:30','13:00–14:00'],answer:'12:30–13:30',explain:'The desk closes from 12:30 until 1:30.'},
   {type:'text',prompt:'Expected arrival time on Thursday: ____',answer:['4:15','4.15','16:15','16.15','four fifteen'],explain:'She expects to arrive at about 4:15.'}
 ]},
 {id:'il-l2-02',stage:2,title:'Parent workshop registration',accent:'en-GB',script:`This Saturday's parent workshop will focus on helping children develop independent study routines. The session begins at ten o'clock, but participants should arrive fifteen minutes early to sign in. It will be held in Room 204 of the community centre, not in the school hall as first announced. Please bring a notebook, because the trainer will give several short planning exercises. Coffee and tea will be provided, but lunch is not included. The workshop finishes at one thirty. If you need childcare, you must request it by Wednesday evening because places are limited.`,q:[
   {type:'choice',prompt:'Where will the workshop take place?',options:['School hall','Room 204, community centre','Library meeting room'],answer:'Room 204, community centre',explain:'The venue changed from the school hall to Room 204.'},
   {type:'text',prompt:'Participants should arrive at ____.',answer:['9:45','9.45','09:45','nine forty-five','nine forty five'],explain:'The workshop starts at 10:00 and participants should arrive 15 minutes early.'},
   {type:'choice',prompt:'What should participants bring?',options:['Lunch','A laptop','A notebook'],answer:'A notebook',explain:'The trainer asks participants to bring a notebook.'},
   {type:'text',prompt:'Childcare must be requested by ____ evening.',answer:['Wednesday','wednesday'],explain:'Childcare requests are due by Wednesday evening.'}
 ]},
 {id:'il-l3-01',stage:3,title:'Research project discussion',accent:'en-GB',script:`The team originally planned to compare students who studied with printed materials against those who used tablets. However, the pilot study showed that device type alone did not explain the difference in recall. The supervisor therefore suggested measuring distraction as a separate variable. The revised project will ask participants to complete the same reading task under two conditions: one with notifications disabled and one with ordinary phone access. The researchers will record reading time and immediate test scores, but they will also contact participants one week later to measure delayed recall. The group agreed that the follow-up measure was essential because short-term performance might overestimate learning.`,q:[
   {type:'choice',prompt:'Why did the team revise the original research question?',options:['Too few students owned tablets','Device type did not explain the recall difference','The reading task was too difficult'],answer:'Device type did not explain the recall difference',explain:'The pilot suggested that device type alone was insufficient.'},
   {type:'choice',prompt:'What new variable will be measured?',options:['Distraction','Age','Reading level'],answer:'Distraction',explain:'The supervisor suggested measuring distraction separately.'},
   {type:'text',prompt:'The second recall test will take place after ____.',answer:['one week','1 week','a week'],explain:'Participants will be contacted one week later.'},
   {type:'choice',prompt:'Why is delayed recall important?',options:['It reduces the number of participants','It may give a better picture of learning','It makes the experiment cheaper'],answer:'It may give a better picture of learning',explain:'Immediate performance can overestimate learning.'}
 ]},
 {id:'il-l3-02',stage:3,title:'Urban transport seminar',accent:'en-GB',script:`The speaker argues that cities often evaluate public transport using only average travel time. This is useful, but incomplete. Reliability may matter just as much, particularly for workers and parents who have fixed arrival times. A bus journey of twenty-five minutes that varies by only two minutes may be more useful than a twenty-minute journey that is frequently delayed by ten or fifteen minutes. The seminar also points out that passenger satisfaction depends on information. When delays are unavoidable, accurate real-time updates can reduce frustration because travellers can change their plans. The speaker recommends that transport authorities publish both average journey times and reliability statistics rather than presenting a single performance figure.`,q:[
   {type:'choice',prompt:'What weakness does the speaker identify in common transport evaluation?',options:['It ignores ticket prices','It focuses too much on average travel time','It measures too many variables'],answer:'It focuses too much on average travel time',explain:'The speaker says average time is useful but incomplete.'},
   {type:'choice',prompt:'Who may especially value reliability?',options:['Tourists with flexible schedules','Workers and parents with fixed arrival times','People who only travel at weekends'],answer:'Workers and parents with fixed arrival times',explain:'Fixed arrival times make reliability especially important.'},
   {type:'text',prompt:'Accurate real-time updates can reduce ____.',answer:['frustration'],explain:'The speaker says updates can reduce frustration.'},
   {type:'choice',prompt:'What should authorities publish?',options:['Only average travel time','Only passenger complaints','Average times and reliability statistics'],answer:'Average times and reliability statistics',explain:'The recommendation is to report both.'}
 ]},
 {id:'il-l4-01',stage:4,title:'Lecture on bilingual learning',accent:'en-GB',script:`Researchers studying bilingual education have moved away from the assumption that using two languages necessarily slows academic development. Current evidence suggests a more complex pattern. Learners may initially retrieve words more slowly in each individual language, especially when vocabulary exposure is divided across contexts. Yet bilingual experience can also strengthen the ability to manage competing information and switch between linguistic systems. Importantly, these effects are not uniform. Age of exposure, proficiency, frequency of use and the social status of each language all influence outcomes. The lecturer warns against comparing bilingual and monolingual children using a single vocabulary test and then drawing broad conclusions about intelligence or learning capacity. A more informative assessment examines growth over time and considers knowledge distributed across both languages.`,q:[
   {type:'choice',prompt:'What older assumption does the lecturer challenge?',options:['Bilingual learners always have larger vocabularies','Using two languages necessarily slows academic development','Children cannot switch between languages'],answer:'Using two languages necessarily slows academic development',explain:'The lecture explicitly moves away from that assumption.'},
   {type:'choice',prompt:'What may bilingual learners initially do more slowly?',options:['Retrieve words in each language','Understand social rules','Learn mathematical concepts'],answer:'Retrieve words in each language',explain:'Word retrieval may be slower when exposure is divided.'},
   {type:'text',prompt:'One factor influencing outcomes is the social ____ of each language.',answer:['status'],explain:'The lecturer lists the social status of each language.'},
   {type:'choice',prompt:'What assessment approach is recommended?',options:['One vocabulary test','Growth over time across both languages','Only testing the stronger language'],answer:'Growth over time across both languages',explain:'The lecturer recommends longitudinal, cross-language assessment.'}
 ]},
 {id:'il-l4-02',stage:4,title:'Lecture on automation and work',accent:'en-GB',script:`Debates about automation often treat jobs as if they were single, indivisible units. In practice, most occupations contain a bundle of tasks, and technologies usually replace or transform some tasks before they eliminate an entire role. This distinction matters because workers may experience automation as job redesign rather than immediate unemployment. Routine information processing is often easier to automate, while tasks requiring trust, negotiation, contextual judgment or responsibility can remain difficult to transfer fully to machines. However, the lecturer cautions that today's technical limits should not be treated as permanent. The most resilient career strategy is therefore not to search for a supposedly automation-proof occupation, but to build the ability to learn new tools, interpret ambiguous situations and combine domain knowledge with human communication.`,q:[
   {type:'choice',prompt:'What mistake is common in debates about automation?',options:['Treating jobs as single units','Ignoring routine work','Focusing on communication skills'],answer:'Treating jobs as single units',explain:'The lecture argues that jobs are bundles of tasks.'},
   {type:'choice',prompt:'Which tasks are described as harder to automate fully?',options:['Routine information processing','Trust and contextual judgment','Basic data entry'],answer:'Trust and contextual judgment',explain:'Trust, negotiation and contextual judgment are highlighted.'},
   {type:'text',prompt:'Workers may experience automation as job ____ rather than immediate unemployment.',answer:['redesign'],explain:'The phrase used is job redesign.'},
   {type:'choice',prompt:'What career strategy does the lecturer recommend?',options:['Find one automation-proof job','Avoid learning new tools','Build adaptable skills and combine domain knowledge with communication'],answer:'Build adaptable skills and combine domain knowledge with communication',explain:'Adaptability and combined skills are the core recommendation.'}
 ]}
];

const IELTS_READING=[
 {id:'ir-l2-01',stage:2,title:'Why small urban parks matter',passage:`Large public parks attract attention because they can contain sports fields, lakes and extensive walking routes. However, researchers in urban planning have increasingly examined much smaller green spaces: pocket parks, planted courtyards and tree-lined sitting areas. Their value is not simply that they add vegetation to a city. Because they can be placed close to homes, schools and workplaces, they may be used more frequently than a distant major park. A ten-minute visit during lunch or after school can become part of an ordinary routine.\n\nAccess, however, is not the same as use. A small park beside a busy road may technically be nearby but feel unpleasant or unsafe. Shade, seating, visibility and pedestrian crossings can therefore influence whether residents actually spend time there. Researchers also warn that green projects can raise nearby property values and, in some cases, contribute to displacement. As a result, measuring success requires more than counting trees. Planners need to ask who uses the space, how often they use it, and whether existing residents continue to benefit over time.`,q:[
   {type:'choice',prompt:'TRUE / FALSE / NOT GIVEN: Small green spaces are always used more often than large parks.',options:['TRUE','FALSE','NOT GIVEN'],answer:'FALSE',explain:'The passage says they may be used more frequently, not always.'},
   {type:'choice',prompt:'Which factor can affect whether a nearby park is actually used?',options:['The number of museums nearby','Shade and seating','The age of surrounding buildings'],answer:'Shade and seating',explain:'Shade and seating are explicitly listed.'},
   {type:'choice',prompt:'What possible negative effect of green projects is mentioned?',options:['Higher property values may contribute to displacement','They always increase traffic','They reduce school attendance'],answer:'Higher property values may contribute to displacement',explain:'The passage mentions displacement as a possible consequence.'},
   {type:'text',prompt:'Complete with ONE WORD: Planners should consider who uses the space and whether existing residents continue to ____.',answer:['benefit'],explain:'The final sentence uses the word benefit.'}
 ]},
 {id:'ir-l2-02',stage:2,title:'The value of rereading less',passage:`Students often believe that a familiar page has been learned because it feels easier to read the second or third time. Psychologists describe this feeling as fluency: information is processed with less effort, so it seems well known. The problem is that ease of processing is not identical to the ability to retrieve information later without the page in front of you.\n\nOne alternative is retrieval practice. After reading a short section, a learner closes the book and tries to write or say the main ideas from memory. This attempt can feel more difficult than rereading, and mistakes are common. Yet the difficulty itself provides useful information. It reveals what has not been learned and strengthens access to what can be recalled. Effective study therefore often alternates exposure and retrieval rather than maximizing either one.`,q:[
   {type:'choice',prompt:'What can make students wrongly believe material has been learned?',options:['The page becomes easier to process','They write too many notes','They study in the morning'],answer:'The page becomes easier to process',explain:'Familiarity can create a misleading feeling of learning.'},
   {type:'choice',prompt:'TRUE / FALSE / NOT GIVEN: Retrieval practice usually feels easier than rereading.',options:['TRUE','FALSE','NOT GIVEN'],answer:'FALSE',explain:'The passage says retrieval can feel more difficult.'},
   {type:'text',prompt:'Complete with ONE WORD: Retrieval attempts reveal what has not been ____.',answer:['learned'],explain:'The passage says retrieval reveals what has not been learned.'},
   {type:'choice',prompt:'What approach does the author recommend?',options:['Only retrieval','Only rereading','Alternating exposure and retrieval'],answer:'Alternating exposure and retrieval',explain:'The final sentence recommends alternating them.'}
 ]},
 {id:'ir-l3-01',stage:3,title:'Remote work and the geography of opportunity',passage:`Remote work was initially discussed as a way to separate employment from location. If employees could work from anywhere, it seemed reasonable to expect that economic opportunity would spread more evenly. The reality has been mixed. Some workers have moved away from expensive centres, and some employers now recruit across wider regions. At the same time, high-paying remote roles remain concentrated among occupations that already require advanced education and digital infrastructure.\n\nLocation also continues to matter for reasons that are difficult to reproduce online. New employees may learn informal norms by observing colleagues, while professional networks can form through repeated low-stakes contact rather than scheduled meetings. Cities also concentrate specialized services and employers, making job changes easier without requiring a household move. For these reasons, remote work may reduce the importance of daily commuting without eliminating the economic value of place.\n\nA more useful question, therefore, is not whether offices will disappear. It is which activities benefit from physical proximity and which can be performed effectively at a distance. Organisations that answer this at task level may make better decisions than those that apply one rule to every employee.`,q:[
   {type:'choice',prompt:'Which heading best matches paragraph 1?',options:['Remote work has produced a mixed redistribution of opportunity','Cities are no longer useful','Digital jobs require less education'],answer:'Remote work has produced a mixed redistribution of opportunity',explain:'Paragraph 1 presents both spreading and concentration of opportunity.'},
   {type:'choice',prompt:'TRUE / FALSE / NOT GIVEN: The passage states that most remote workers have moved out of expensive cities.',options:['TRUE','FALSE','NOT GIVEN'],answer:'NOT GIVEN',explain:'It says some workers moved, not most.'},
   {type:'choice',prompt:'Why can cities still help people change jobs?',options:['They guarantee higher salaries','They concentrate employers and services','They eliminate the need for networking'],answer:'They concentrate employers and services',explain:'The passage explicitly links concentration to easier job changes.'},
   {type:'text',prompt:'Complete with ONE WORD: Organisations should evaluate remote work at the ____ level.',answer:['task'],explain:'The final sentence refers to task level.'}
 ]},
 {id:'ir-l3-02',stage:3,title:'When choice becomes cognitive work',passage:`Consumer choice is often treated as an unqualified benefit. More options should, in theory, allow people to select products that match their preferences more precisely. Yet choice also imposes cognitive work. Every additional option creates another item to compare, another possible trade-off and another opportunity to worry about making the wrong decision.\n\nThis does not mean that fewer choices are always better. The effect depends on how alternatives are organised and how familiar the decision is. Experts can ignore irrelevant features because they know which criteria matter. Novices may struggle because they have not yet developed a useful mental model. Good design can reduce this burden by grouping similar options, providing sensible defaults and revealing complexity only when users request it.\n\nThe broader lesson is that freedom and friction are not opposites. A system can preserve meaningful choice while reducing unnecessary decisions. In digital products, this often means designing a clear next action rather than placing every possible function on the first screen.`,q:[
   {type:'choice',prompt:'What is the main point of paragraph 1?',options:['More choice can require more mental effort','Consumers dislike all choices','Products are becoming cheaper'],answer:'More choice can require more mental effort',explain:'The paragraph focuses on cognitive work and trade-offs.'},
   {type:'choice',prompt:'Why may experts manage many options better than novices?',options:['They have more free time','They know which criteria matter','They always prefer defaults'],answer:'They know which criteria matter',explain:'Experts can ignore irrelevant features.'},
   {type:'choice',prompt:'TRUE / FALSE / NOT GIVEN: The author argues that fewer choices are always preferable.',options:['TRUE','FALSE','NOT GIVEN'],answer:'FALSE',explain:'The passage explicitly says fewer choices are not always better.'},
   {type:'text',prompt:'Complete with ONE WORD: Good design can provide sensible ____.',answer:['defaults'],explain:'The word defaults appears in paragraph 2.'}
 ]},
 {id:'ir-l4-01',stage:4,title:'The problem with measuring productivity',passage:`Productivity appears to be a simple concept: output divided by input. At the level of a factory producing identical objects, this ratio can be highly informative. In knowledge work, however, both sides of the equation become harder to define. An engineer may spend a week preventing a failure that never occurs. A teacher may influence a student's decisions years later. A manager may improve a process by reducing unnecessary work rather than increasing visible activity.\n\nDigital workplaces nevertheless generate abundant measurable traces: messages sent, tickets closed, hours online and documents edited. Their availability can tempt organisations to use them as proxies for productivity. The danger is not merely that a proxy may be inaccurate. Once workers know which behaviour is measured, they may adapt to the metric itself. A target intended to represent useful work can then begin to distort it.\n\nThis does not imply that measurement should be abandoned. Instead, metrics should be treated as partial evidence and combined with judgment about quality, outcomes and context. Measures are most useful when they support a question rather than replace one.`,q:[
   {type:'choice',prompt:'Why is productivity harder to define in knowledge work?',options:['Knowledge workers dislike measurement','Inputs and outputs may be difficult to observe directly','Factories have no measurable output'],answer:'Inputs and outputs may be difficult to observe directly',explain:'The examples show delayed, prevented or qualitative outcomes.'},
   {type:'choice',prompt:'What danger arises when workers know the metric being used?',options:['They may adapt behaviour to the metric','They may stop using digital tools','They may work fewer hours'],answer:'They may adapt behaviour to the metric',explain:'The passage says behaviour may shift toward the measure itself.'},
   {type:'choice',prompt:'TRUE / FALSE / NOT GIVEN: The author recommends abandoning productivity metrics.',options:['TRUE','FALSE','NOT GIVEN'],answer:'FALSE',explain:'The author recommends treating metrics as partial evidence.'},
   {type:'text',prompt:'Complete with ONE WORD: Metrics should support a question rather than ____ one.',answer:['replace'],explain:'The final sentence says measures should support rather than replace a question.'}
 ]},
 {id:'ir-l4-02',stage:4,title:'Why predictions change the systems they describe',passage:`Forecasting is easiest when the act of making a prediction does not influence the thing being predicted. Weather forecasts mostly satisfy this condition: announcing a storm does not create the storm. Social systems are different. A prediction about human behaviour can alter expectations, incentives and decisions, thereby changing the outcome itself.\n\nConsider a forecast that a neighbourhood will soon become expensive. Potential buyers may rush to purchase property before prices rise, helping to produce the increase that was predicted. The reverse can also happen. If authorities predict severe congestion and people respond by changing travel times, the forecast may appear exaggerated precisely because it successfully changed behaviour.\n\nThese feedback effects make social prediction difficult to evaluate. A forecast that seems wrong may have prevented the event it warned about, while an accurate forecast may partly have caused the outcome. Analysts therefore need to distinguish between predictions that merely describe a likely future and interventions that become part of the causal system.`,q:[
   {type:'choice',prompt:'Why are social forecasts different from weather forecasts?',options:['Social predictions can influence behaviour','Weather data are always more accurate','People do not understand weather forecasts'],answer:'Social predictions can influence behaviour',explain:'Predictions can change expectations and decisions.'},
   {type:'choice',prompt:'What example illustrates a self-fulfilling prediction?',options:['People travel later to avoid congestion','Buyers rush into a neighbourhood expected to become expensive','A storm arrives after a forecast'],answer:'Buyers rush into a neighbourhood expected to become expensive',explain:'Their action can contribute to the predicted price increase.'},
   {type:'choice',prompt:'TRUE / FALSE / NOT GIVEN: A forecast that appears inaccurate may still have been useful.',options:['TRUE','FALSE','NOT GIVEN'],answer:'TRUE',explain:'It may have changed behaviour and prevented the event.'},
   {type:'text',prompt:'Complete with ONE WORD: Analysts should distinguish description from causal ____.',answer:['interventions','intervention'],explain:'The passage contrasts prediction with interventions in the causal system.'}
 ]}
];

const IELTS_WRITING=[
 {id:'iw-1-01',stage:1,task:2,title:'Learning languages in adulthood',prompt:'Some people believe adults can learn a new language effectively only by living in a country where it is spoken. To what extent do you agree or disagree?',scaffold:['Write a clear one-sentence position.','Give one reason from daily life or study.','Add one specific example.'],partial:true},
 {id:'iw-1-02',stage:1,task:1,title:'Weekly study time',prompt:'The table shows the average weekly hours spent on four learning activities by a group of adult language learners.',chart:{headers:['Activity','Hours/week'],rows:[['Listening','3.5'],['Reading','2.5'],['Speaking practice','1.5'],['Writing','1.0']]},scaffold:['Write one overview sentence: what is highest and lowest?','Write two comparison sentences.','Do not explain why the numbers are different.'],partial:true},
 {id:'iw-2-01',stage:2,task:2,title:'Public transport and private cars',prompt:'Some cities try to reduce traffic by making public transport cheaper. Others believe charging drivers more is more effective. Discuss both views and give your own opinion.',scaffold:['Plan two body paragraphs before writing.','Each paragraph: main idea → explanation → example.','State your own position clearly.']},
 {id:'iw-2-02',stage:2,task:1,title:'Library visits by age group',prompt:'The table shows the average number of public-library visits per person per year in four age groups.',chart:{headers:['Age group','Visits/year'],rows:[['15–24','8'],['25–39','11'],['40–59','9'],['60+','14']]},scaffold:['Overview first: identify the overall high/low pattern.','Group similar values instead of listing every number mechanically.','Use comparison language accurately.']},
 {id:'iw-2-03',stage:2,task:2,title:'Online courses and universities',prompt:'Online courses give people greater access to education, but some people think they can never replace face-to-face university teaching. Discuss both views and give your own opinion.',scaffold:['Avoid memorised introductions.','Use one concrete example per body paragraph.','Conclude by restating, not introducing a new idea.']},
 {id:'iw-3-01',stage:3,task:1,title:'Commute mode changes',prompt:'The table compares the percentage of employees using four commuting methods in one European city in 2015 and 2025.',chart:{headers:['Mode','2015','2025'],rows:[['Car','48%','35%'],['Public transport','31%','38%'],['Bicycle','9%','15%'],['Walking','12%','12%']]},scaffold:['20 minutes.','At least 150 words.','Select key features; do not describe every cell equally.']},
 {id:'iw-3-02',stage:3,task:2,title:'Artificial intelligence at work',prompt:'As artificial intelligence becomes more capable, some tasks currently done by people will be automated. Is this development more beneficial or more harmful for society?',scaffold:['40 minutes.','At least 250 words.','Develop a clear position with specific support rather than a list of ideas.']},
 {id:'iw-3-03',stage:3,task:2,title:'Children and unstructured time',prompt:'Some parents organise many lessons and activities for their children, while others believe children need more unstructured free time. Discuss both views and give your own opinion.',scaffold:['40 minutes.','Use precise claims: avoid saying all children or all parents.','Check paragraph progression at the end.']},
 {id:'iw-4-01',stage:4,task:1,title:'Remote-work frequency',prompt:'The table shows the percentage of employees in four sectors who worked from home at least two days per week in 2019 and 2026.',chart:{headers:['Sector','2019','2026'],rows:[['Finance','12%','46%'],['Education','8%','28%'],['Technology','24%','62%'],['Healthcare','5%','14%']]},scaffold:['Strict 20-minute target.','At least 150 words.','Aim for a clear overview and selective, accurate comparisons.']},
 {id:'iw-4-02',stage:4,task:2,title:'University education and employment',prompt:'Universities should focus mainly on preparing students for employment rather than providing a broad academic education. To what extent do you agree or disagree?',scaffold:['Strict 40-minute target.','At least 250 words.','Aim for a fully developed position, precise vocabulary and varied accurate structures.']},
 {id:'iw-4-03',stage:4,task:2,title:'Cities and family life',prompt:'Large cities offer more opportunities, but they can also make family life more difficult. What problems can urban families face, and what measures could help address them?',scaffold:['Strict 40-minute target.','Answer both parts directly.','Prioritise depth and support over the number of ideas.']}
];

const IELTS_SPEAKING=[
 {id:'is-1-01',stage:1,title:'Home and neighbourhood',part1:['What do you like most about the area where you live?','Is there anything you would like to change about your neighbourhood?','How often do you use public spaces such as parks or libraries?'],cue:null,part3:[]},
 {id:'is-1-02',stage:1,title:'Learning English',part1:['When do you usually use English in daily life?','Which part of learning English is most difficult for you?','Do you prefer studying alone or with another person? Why?'],cue:null,part3:[]},
 {id:'is-2-01',stage:2,title:'A useful place',part1:['Do you often visit libraries or cafés?','What kind of place helps you concentrate?'],cue:{title:'Describe a place where you can study or think well.',bullets:['where it is','what it is like','what you usually do there','why it helps you focus']},part3:['Why do some people work better outside their homes?']},
 {id:'is-2-02',stage:2,title:'A skill you are learning',part1:['Do you enjoy learning new skills?','How do you decide whether a course is worth continuing?'],cue:{title:'Describe a skill you are currently trying to improve.',bullets:['what the skill is','why you chose it','how you practise it','what has been difficult']},part3:['Do adults learn skills differently from children?']},
 {id:'is-3-01',stage:3,title:'Technology and communication',part1:['How often do you use technology to communicate with other people?','Has your use of technology changed in recent years?'],cue:{title:'Describe a piece of technology that has changed how you learn or work.',bullets:['what it is','when you started using it','how you use it','why it has been important']},part3:['What communication skills may become more important as AI develops?','Should schools teach students how to evaluate information produced by AI? Why?']},
 {id:'is-3-02',stage:3,title:'Living in another country',part1:['What do people usually find difficult when they move to a new place?','Is it important to learn the local language?'],cue:{title:'Describe an experience that helped you understand a different culture.',bullets:['what happened','where it happened','who was involved','what you learned from it']},part3:['How can cities help newcomers become part of the local community?','Can living abroad change a person’s identity? In what ways?']},
 {id:'is-4-01',stage:4,title:'Education mini-mock',part1:['What kind of learning do you enjoy most?','Did you enjoy studying when you were younger?','How has technology changed the way you learn?'],cue:{title:'Describe a teacher, course or learning experience that changed the way you think.',bullets:['what it was','when it happened','what you learned','why it had a lasting effect']},part3:['What should be the main purpose of university education?','How should education systems respond when technology changes the labour market?','Do qualifications accurately show what a person can do? Why or why not?']},
 {id:'is-4-02',stage:4,title:'Cities mini-mock',part1:['Do you prefer living in a large city or a small town?','What is the most convenient thing about where you live?','What makes a city attractive to families?'],cue:{title:'Describe a city or neighbourhood that made a strong impression on you.',bullets:['where it was','what you noticed','what you did there','why you remember it clearly']},part3:['Why do some cities feel more liveable than others?','Should governments limit car use in city centres?','How might cities change if more people work remotely?']}
];

let ieltsCurrent=null,ieltsRec=null,ieltsRecStart=0,ieltsTranscript='';
function iState(){
  if(!st.ielts)st.ielts={stages:{listening:2,reading:2,writing:1,speaking:1},history:[],week:{},lastBySkill:{},startedAt:new Date().toISOString()};
  if(!st.ielts.stages)st.ielts.stages={listening:2,reading:2,writing:1,speaking:1};
  if(!st.ielts.history)st.ielts.history=[];if(!st.ielts.week)st.ielts.week={};if(!st.ielts.lastBySkill)st.ielts.lastBySkill={};
  return st.ielts;
}
function iWeekKey(){return typeof weekKey==='function'?weekKey():hDateKey()}
function iRecent(skill,stage){return iState().history.filter(x=>x.skill===skill&&x.stage===stage).slice(-4)}
function iRecommend(){
  const s=iState(),skills=['writing','speaking','listening','reading'];
  return skills.slice().sort((a,b)=>s.stages[a]-s.stages[b] || iRecent(a,s.stages[a]).length-iRecent(b,s.stages[b]).length)[0];
}
function iInject(){
  if(document.getElementById('ieltsHome')){iHome();return}
  const css=document.createElement('style');css.textContent=`.ieltsCard{border:2px solid #d9e1ee}.ieltsGrid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.ieltsSkill{padding:12px;border:1px solid var(--line);border-radius:14px;background:#fafaf8}.ieltsSkill b{display:block;font-size:17px;margin:4px 0}.ieltsStage{font-size:12px;color:var(--muted)}.ieltsQuestion{border-top:1px solid var(--line);padding:14px 0}.ieltsQuestion:first-child{border-top:0}.ieltsPassage{font-family:Georgia,"Times New Roman",serif;font-size:18px;line-height:1.75;white-space:pre-line}.ieltsTable{width:100%;border-collapse:collapse;margin:12px 0}.ieltsTable th,.ieltsTable td{border:1px solid var(--line);padding:9px;text-align:center}.ieltsTimer{font-size:30px;font-weight:700}.ieltsRubric{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.ieltsRubric>div{background:var(--soft);padding:10px;border-radius:10px}.ieltsNav{display:flex;gap:8px;flex-wrap:wrap}@media(max-width:620px){.ieltsGrid{grid-template-columns:repeat(2,1fr)}.ieltsRubric{grid-template-columns:1fr}}`;document.head.appendChild(css);
  const home=document.createElement('div');home.id='ieltsHome';home.className='card ieltsCard';
  const box=document.createElement('div');box.id='ieltsBox';box.className='card hidden';
  const anchor=document.getElementById('phraseRecallBox')||document.getElementById('habitPanel');
  anchor.insertAdjacentElement('afterend',box);box.insertAdjacentElement('beforebegin',home);iHome();
}
function iHome(){
  const el=document.getElementById('ieltsHome');if(!el)return;const s=iState(),wk=s.week[iWeekKey()]||0,rec=iRecommend();
  const cards=['listening','reading','writing','speaking'].map(k=>`<button class="ieltsSkill" onclick="iOpen('${k}')"><span>${IELTS_ICON[k]}</span><b>${IELTS_SKILL_NAMES[k]}</b><span class="ieltsStage">${IELTS_STAGE_NAMES[s.stages[k]]}</span></button>`).join('');
  el.innerHTML=`<div class="row" style="justify-content:space-between;align-items:flex-start"><div><span class="pill">NEW・v1.5</span><h2 style="margin:8px 0 4px">🎯 IELTS Academic 7.5–8 Track</h2><p class="small" style="margin:0">原本 English Gym 繼續；這條路線專練 IELTS 題型。建議每週 3 次，不需要每天兩套都做。</p></div><div class="metric miniMetric"><span class="small">本週 IELTS</span><b>${wk}/3</b><span class="small">次</span></div></div><div class="tip" style="margin:12px 0"><b>今天建議：</b>${IELTS_ICON[rec]} ${IELTS_SKILL_NAMES[rec]}・${IELTS_STAGE_NAMES[s.stages[rec]]}<br><span class="small">依目前各技能階段，自動優先補較弱輸出。</span></div><div class="ieltsGrid">${cards}</div><p class="small">訓練階段不是 IELTS 預測分數。Listening/Reading 會客觀計分；Writing/Speaking 不用假分數騙你，改用官方評分面向＋深度批改。</p>`;
}
function iPool(skill){const stg=iState().stages[skill];return skill==='listening'?IELTS_LISTENING.filter(x=>x.stage===stg):skill==='reading'?IELTS_READING.filter(x=>x.stage===stg):skill==='writing'?IELTS_WRITING.filter(x=>x.stage===stg):IELTS_SPEAKING.filter(x=>x.stage===stg)}
function iPick(skill){const pool=iPool(skill),last=iState().lastBySkill[skill];let cand=pool.filter(x=>x.id!==last);if(!cand.length)cand=pool;const x=cand[Math.floor(Math.random()*cand.length)]||pool[0];iState().lastBySkill[skill]=x?.id||'';return x}
function iOpen(skill){ieltsCurrent={skill,item:iPick(skill)};const box=document.getElementById('ieltsBox');box.classList.remove('hidden');box.scrollIntoView({behavior:'smooth',block:'start'});if(skill==='listening')iRenderListening();else if(skill==='reading')iRenderReading();else if(skill==='writing')iRenderWriting();else iRenderSpeaking()}
function iClose(){document.getElementById('ieltsBox')?.classList.add('hidden');if(ieltsRec){try{ieltsRec.abort()}catch{}ieltsRec=null}}
function iHeader(skill,item){return `<div class="row" style="justify-content:space-between"><div><span class="pill">${IELTS_ICON[skill]} ${IELTS_SKILL_NAMES[skill]}</span> <span class="pill">${IELTS_STAGE_NAMES[item.stage]}</span></div><button onclick="iClose()">關閉</button></div><h2>${esc(item.title)}</h2><p class="small">IELTS-style 原創練習，依官方題型設計；不是官方考題，也不是預測分數。</p>`}
function iQuestions(qs){return qs.map((q,i)=>`<div class="ieltsQuestion"><b>${i+1}. ${esc(q.prompt)}</b>${q.type==='choice'?`<select id="iq${i}"><option value="">請選擇</option>${q.options.map(o=>`<option value="${esc(o)}">${esc(o)}</option>`).join('')}</select>`:`<input id="iq${i}" autocomplete="off" placeholder="輸入答案" />`}<div id="ie${i}" class="small"></div></div>`).join('')}
function iNorm(s){return String(s||'').toLowerCase().trim().replace(/[.,]/g,'').replace(/\s+/g,' ')}
function iCorrect(v,q){const ans=Array.isArray(q.answer)?q.answer:[q.answer];return ans.some(a=>iNorm(v)===iNorm(a))}
function iRenderListening(){const a=ieltsCurrent.item,stage=a.stage,plays=stage>=3?1:2;ieltsCurrent.playsLeft=plays;document.getElementById('ieltsBox').innerHTML=`${iHeader('listening',a)}<div class="tip"><b>考試習慣：</b>${stage>=3?'只播 1 次。先讀題，再聽關鍵資訊。':'這一階段可播 2 次；先建立定位關鍵字的習慣，之後會縮成 1 次。'}</div><div class="row" style="margin:12px 0"><button id="ieltsPlay" class="primary" onclick="iPlayListening()">▶ 播放錄音</button><span id="ieltsPlayCount" class="small">剩 ${plays} 次</span></div>${iQuestions(a.q)}<button class="primary" onclick="iCheckObjective()">交卷＋看答案</button><div id="ieltsResult"></div>`}
function iVoice(lang='en-GB'){const vs=speechSynthesis.getVoices();return vs.find(v=>v.lang===lang&&/Google|Microsoft|Daniel|Serena|Samantha|Natural/i.test(v.name))||vs.find(v=>v.lang===lang)||vs.find(v=>v.lang.startsWith('en'))}
function iPlayListening(){if(!ieltsCurrent?.playsLeft)return;ieltsCurrent.playsLeft--;const a=ieltsCurrent.item,u=new SpeechSynthesisUtterance(a.script);u.lang=a.accent||'en-GB';u.rate=a.stage>=4?.98:.92;const v=iVoice(u.lang);if(v)u.voice=v;speechSynthesis.cancel();speechSynthesis.speak(u);const c=document.getElementById('ieltsPlayCount');if(c)c.textContent='剩 '+ieltsCurrent.playsLeft+' 次';if(!ieltsCurrent.playsLeft){const b=document.getElementById('ieltsPlay');if(b)b.disabled=true}}
function iRenderReading(){const a=ieltsCurrent.item;document.getElementById('ieltsBox').innerHTML=`${iHeader('reading',a)}<div class="tip"><b>策略：</b>先讀題目找定位詞，再回文章找證據。TRUE/FALSE/NOT GIVEN 只看文章，不靠常識。</div><article class="ieltsPassage">${esc(a.passage)}</article>${iQuestions(a.q)}<button class="primary" onclick="iCheckObjective()">交卷＋看答案</button><div id="ieltsResult"></div>`}
async function iCheckObjective(){const {skill,item}=ieltsCurrent;let hit=0;item.q.forEach((q,i)=>{const v=document.getElementById('iq'+i)?.value||'',ok=iCorrect(v,q);if(ok)hit++;document.getElementById('ie'+i).innerHTML=`<span class="${ok?'good':'warn'}">${ok?'✅ 正確':'✦ 答案：'+esc(Array.isArray(q.answer)?q.answer[0]:q.answer)}</span>　${esc(q.explain)}`});const score=Math.round(hit/item.q.length*100);await iRecord(skill,item.stage,score,'objective');document.getElementById('ieltsResult').innerHTML=`<div class="tip" style="margin-top:12px"><h3>${score}%</h3><p>${score>=75?'這組已達目前階段標準。':'先看錯在哪個「定位／同義改寫／細節」；不用立刻刷更多題。'}</p><button onclick="iClose()">完成今天這組</button></div>`}
function iChart(c){if(!c)return'';return `<table class="ieltsTable"><thead><tr>${c.headers.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${c.rows.map(r=>`<tr>${r.map(x=>`<td>${esc(x)}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
function iWritingLimits(a){if(a.stage===1)return a.task===1?{min:70,time:12,label:'先寫 overview＋2 個比較，不要求完整 150 字'}:{min:120,time:15,label:'先寫立場＋1 個完整 body paragraph'};return a.task===1?{min:150,time:20,label:'完整 Task 1・至少 150 字'}:{min:250,time:40,label:'完整 Task 2・至少 250 字'}}
function iRenderWriting(){const a=ieltsCurrent.item,l=iWritingLimits(a);ieltsCurrent.started=0;document.getElementById('ieltsBox').innerHTML=`${iHeader('writing',a)}<div class="row"><span class="pill">Academic Task ${a.task}</span><span class="pill">目標 ${l.time} 分鐘</span><span class="pill">${esc(l.label)}</span></div><div class="tip" style="margin-top:12px"><b>題目</b><p>${esc(a.prompt)}</p>${iChart(a.chart)}</div>${a.stage<=2?`<div class="tip"><b>這階段可以用鷹架：</b><ul>${a.scaffold.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`:''}<div class="row" style="margin:12px 0"><button class="primary" onclick="iWritingTimer()">開始計時</button><span id="iwTimer" class="ieltsTimer">0:00</span></div><textarea id="iwText" style="min-height:260px" oninput="iWritingCount()" placeholder="直接在這裡寫。先完成，再修正。"></textarea><p class="small"><span id="iwCount">0</span> words</p><div class="ieltsRubric"><div><b>Task response / achievement</b><br><span class="small">有直接回答題目／Task 1 有清楚 overview。</span></div><div><b>Coherence & cohesion</b><br><span class="small">段落有功能，想法順序清楚，不堆連接詞。</span></div><div><b>Lexical resource</b><br><span class="small">詞彙精準、搭配自然，不為了難字犧牲正確。</span></div><div><b>Grammar range & accuracy</b><br><span class="small">簡單＋複雜句都能控制，錯誤不要反覆。</span></div></div><div class="row" style="margin-top:12px"><button class="primary" onclick="iWritingReview()">完成＋檢查</button><button onclick="iCopyWriting()">🧠 複製給 ChatGPT IELTS 批改</button></div><div id="iwResult"></div>`}
function iWritingCount(){const t=document.getElementById('iwText')?.value||'',n=t.trim()?t.trim().split(/\s+/).length:0;document.getElementById('iwCount').textContent=n}
function iWritingTimer(){if(ieltsCurrent.started)return;ieltsCurrent.started=Date.now();clearInterval(ieltsCurrent.timer);ieltsCurrent.timer=setInterval(()=>{const sec=Math.floor((Date.now()-ieltsCurrent.started)/1000),m=Math.floor(sec/60),s=String(sec%60).padStart(2,'0');const el=document.getElementById('iwTimer');if(el)el.textContent=`${m}:${s}`},500)}
function iWritingReview(){const a=ieltsCurrent.item,l=iWritingLimits(a),t=document.getElementById('iwText')?.value.trim()||'',n=t?t.split(/\s+/).length:0;if(!t){document.getElementById('iwResult').innerHTML='<div class="error">先寫一點再完成。今天只寫最低版本也可以。</div>';return}clearInterval(ieltsCurrent.timer);document.getElementById('iwResult').innerHTML=`<div class="tip"><h3>先做 60 秒自我檢查</h3><label><input type="checkbox"> 我直接回答題目／有清楚 overview</label><br><label><input type="checkbox"> 每一段只有一個主要功能</label><br><label><input type="checkbox"> 我有具體支持，不只是空泛意見</label><br><label><input type="checkbox"> 我檢查了重複出現的文法錯誤</label><p class="${n>=l.min?'good':'warn'}"><b>${n} words</b> ${n>=l.min?'✓ 達到這階段字數目標':'— 這次先完成即可，下次再靠近 '+l.min+' 字'}</p><p><b>完成後只選一個感受：</b></p><div class="row"><button onclick="iProductiveDone('writing','hard')">很卡</button><button class="primary" onclick="iProductiveDone('writing','right')">可完成</button><button onclick="iProductiveDone('writing','easy')">穩定</button></div></div>`}
function iWritingPrompt(){const a=ieltsCurrent.item,t=document.getElementById('iwText')?.value.trim()||'';return `你是 IELTS Academic Writing 教練。請依官方 IELTS Writing band descriptors 評估，但只給「粗估 band range」，不要假裝精準。\nTask ${a.task}: ${a.prompt}\n我的答案：\n${t}\n\n請依序輸出：1) 粗估 band range 2) Task ${a.task===1?'Achievement':'Response'} / Coherence & Cohesion / Lexical Resource / Grammatical Range & Accuracy 四項分析 3) 最影響分數的 2 個問題 4) 只改最必要錯誤的版本 5) 一個接近 Band 7.5–8 的自然版本（不要故意堆難字）6) 給我一個 10 分鐘 rewrite 任務。`}
async function iCopyWriting(){const p=iWritingPrompt();try{await navigator.clipboard.writeText(p);hToast('已複製 IELTS Writing 批改指令。貼到 ChatGPT 即可。')}catch{prompt('複製到 ChatGPT：',p)}}
function iSpeakingTarget(stage){return stage===1?'約 60–90 秒・只練熟悉 Part 1':stage===2?'約 2–3 分鐘・加入 Part 2':stage===3?'約 4–5 分鐘・Part 2＋Part 3': '約 8–10 分鐘 mini-mock・三部分都練'}
function iRenderSpeaking(){const a=ieltsCurrent.item;ieltsTranscript='';document.getElementById('ieltsBox').innerHTML=`${iHeader('speaking',a)}<div class="tip"><b>這階段：</b>${iSpeakingTarget(a.stage)}。先把意思講完，再修自然度。</div><h3>Part 1</h3><ol>${a.part1.map(x=>`<li>${esc(x)}</li>`).join('')}</ol>${a.cue?`<h3>Part 2 Cue Card</h3><div class="tip"><b>${esc(a.cue.title)}</b><ul>${a.cue.bullets.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><span class="small">正式 IELTS Part 2 會有準備時間；這裡先給自己 1 分鐘列 3–5 個關鍵字。</span></div>`:''}${a.part3.length?`<h3>Part 3</h3><ol>${a.part3.map(x=>`<li>${esc(x)}</li>`).join('')}</ol>`:''}<div class="row" style="margin:12px 0"><button class="primary" onclick="iSpeakStart()">🎙️ 開始整段回答</button><button onclick="iSpeakStop()">⏹ 停止</button><span id="isTimer" class="ieltsTimer">0:00</span></div><p class="small">瀏覽器若支援，會把你的英文轉成文字。原始錄音不會存進 English Gym。</p><textarea id="isText" style="min-height:180px" placeholder="語音轉錄會出現在這裡；也可以自己輸入。"></textarea><div class="row"><button class="primary" onclick="iSpeakingReview()">完成＋看練習訊號</button><button onclick="iCopySpeaking()">🧠 複製給 ChatGPT IELTS 批改</button></div><div id="isResult"></div>`}
function iSpeakStart(){const box=document.getElementById('isText');if(box)box.value='';ieltsRecStart=Date.now();clearInterval(ieltsCurrent.timer);ieltsCurrent.timer=setInterval(()=>{const sec=Math.floor((Date.now()-ieltsRecStart)/1000),m=Math.floor(sec/60),s=String(sec%60).padStart(2,'0');const el=document.getElementById('isTimer');if(el)el.textContent=`${m}:${s}`},500);const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){box?.focus();hToast('此瀏覽器不支援自動轉文字，直接輸入即可。');return}ieltsRec=new R();ieltsRec.lang='en-US';ieltsRec.interimResults=true;ieltsRec.continuous=true;ieltsRec.onresult=e=>{let s='';for(let i=0;i<e.results.length;i++)s+=e.results[i][0].transcript+' ';if(box)box.value=s.trim()};ieltsRec.onerror=()=>hToast('語音辨識沒有成功，可直接輸入剛才說的內容。');try{ieltsRec.start()}catch{}}
function iSpeakStop(){clearInterval(ieltsCurrent.timer);if(ieltsRec){try{ieltsRec.stop()}catch{}ieltsRec=null}}
function iSpeakingSignals(t){const w=t.trim()?t.trim().split(/\s+/):[],lower=' '+iNorm(t)+' ',fill=w.filter(x=>['um','uh','like','actually','basically'].includes(iNorm(x))).length,con=['because','however','although','for example','therefore','while','whereas'].filter(x=>lower.includes(' '+x+' ')).length;return {words:w.length,unique:new Set(w.map(iNorm)).size,fill,con}}
function iSpeakingReview(){iSpeakStop();const t=document.getElementById('isText')?.value.trim()||'';if(!t){document.getElementById('isResult').innerHTML='<div class="error">還沒有轉錄文字。先說或輸入一小段。</div>';return}const s=iSpeakingSignals(t),ratio=s.words?s.unique/s.words:0;document.getElementById('isResult').innerHTML=`<div class="tip"><h3>這不是 band 分數，是練習訊號</h3><p><b>${s.words}</b> words・詞彙變化約 ${Math.round(ratio*100)}%・連接訊號 ${s.con}・常見 filler ${s.fill}</p><p><b>下一次只修一件：</b>${s.words<45?'把答案延長：Point → reason → example。':s.con<1?'至少清楚連接一個原因或例子。':s.fill>4?'用短暫停頓取代 filler。':'保持內容完整，再讓用字更精準。'}</p><p class="small">Pronunciation 無法從文字可靠評分，所以系統不會亂給你假分數。</p><p><b>完成後選感受：</b></p><div class="row"><button onclick="iProductiveDone('speaking','hard')">很卡</button><button class="primary" onclick="iProductiveDone('speaking','right')">可完成</button><button onclick="iProductiveDone('speaking','easy')">穩定</button></div></div>`}
function iSpeakingPrompt(){const a=ieltsCurrent.item,t=document.getElementById('isText')?.value.trim()||'';return `你是 IELTS Speaking 教練。請依官方 IELTS Speaking band descriptors 分析這份「文字轉錄」，只給粗估 band range。因為沒有音訊，Pronunciation 請明確標示「無法從轉錄可靠評估」，不要虛構。\n題目：\nPart 1: ${a.part1.join(' / ')}\n${a.cue?'Part 2: '+a.cue.title+' '+a.cue.bullets.join(', '):''}\n${a.part3.length?'Part 3: '+a.part3.join(' / '):''}\n我的轉錄：\n${t}\n\n請輸出：1) 粗估 band range（只依文字可判斷部分）2) Fluency & Coherence / Lexical Resource / Grammatical Range & Accuracy；Pronunciation 標示無法可靠評估 3) 最重要 2 個問題 4) Minimal correction 5) Natural version 6) 接近 Band 7.5–8、但不故意艱深的版本 7) 30–60 秒 retry 任務。`}
async function iCopySpeaking(){const p=iSpeakingPrompt();try{await navigator.clipboard.writeText(p);hToast('已複製 IELTS Speaking 批改指令。貼到 ChatGPT 即可。')}catch{prompt('複製到 ChatGPT：',p)}}
async function iRecord(skill,stage,score,kind,rating=null){const s=iState();s.history.push({date:new Date().toISOString(),skill,stage,score,kind,rating});if(s.history.length>300)s.history=s.history.slice(-300);const wk=iWeekKey();s.week[wk]=(s.week[wk]||0)+1;iMaybeAdvance(skill);await save();if(typeof hMark==='function')await hMark('ielts');iHome()}
function iMaybeAdvance(skill){const s=iState(),stage=s.stages[skill];if(stage>=4)return;const r=iRecent(skill,stage);if(skill==='listening'||skill==='reading'){if(r.length>=3){const avg=r.reduce((a,b)=>a+(b.score||0),0)/r.length;if(avg>=75)s.stages[skill]=stage+1}}else if(r.length>=4){const stable=r.filter(x=>x.rating==='right'||x.rating==='easy').length;if(stable>=3)s.stages[skill]=stage+1}}
async function iProductiveDone(skill,rating){const a=ieltsCurrent.item;await iRecord(skill,a.stage,null,'productive',rating);const box=document.getElementById(skill==='writing'?'iwResult':'isResult');if(box)box.innerHTML=`<div class="tip"><h3>✅ 今天 IELTS ${IELTS_SKILL_NAMES[skill]} 完成</h3><p>不用再加題。系統會在幾次穩定完成後才提高階段。</p><button onclick="iClose()">完成</button></div>`}

window.addEventListener('load',()=>setTimeout(iInject,700));
setTimeout(iInject,900);
