window.ENGLISH_GYM_SENTENCES=[
{id:'l1-01',d:1,topic:'daily',t:'I need a little more time.'},
{id:'l1-02',d:1,topic:'daily',t:'Could you say that again, please?'},
{id:'l1-03',d:1,topic:'daily',t:'I am still learning how to explain this in English.'},
{id:'l1-04',d:1,topic:'geneva',t:'I usually take the bus when I go into the city.'},
{id:'l1-05',d:1,topic:'school',t:'My son has no school on Wednesday.'},
{id:'l1-06',d:1,topic:'work',t:'I would like to ask one more question.'},
{id:'l2-01',d:2,topic:'learning',t:'My goal is to speak more clearly without translating every word first.'},
{id:'l2-02',d:2,topic:'school',t:'I want to feel more confident when I talk to teachers and other parents.'},
{id:'l2-03',d:2,topic:'work',t:'I am looking for a practical way to improve my English for work.'},
{id:'l2-04',d:2,topic:'learning',t:'Short practice sessions are easier for me to continue every day.'},
{id:'l2-05',d:2,topic:'geneva',t:'Living in Geneva gives me many chances to hear different accents.'},
{id:'l2-06',d:2,topic:'daily',t:'I can understand the main idea even when I miss a few words.'},
{id:'l3-01',d:3,topic:'learning',t:'I understand most of the conversation, but I still need more time to answer clearly.'},
{id:'l3-02',d:3,topic:'unige',t:'I am improving my English so that I can study and work in an international environment.'},
{id:'l3-03',d:3,topic:'learning',t:'When I feel tired, a shorter practice session helps me continue without giving up.'},
{id:'l3-04',d:3,topic:'work',t:'I want to explain my experience clearly instead of giving very short answers in interviews.'},
{id:'l3-05',d:3,topic:'school',t:'When I speak with a teacher, I want to ask clear questions and remember the important details.'},
{id:'l3-06',d:3,topic:'ai',t:'I use technology to reduce repetitive work and save my attention for more important tasks.'},
{id:'l4-01',d:4,topic:'learning',t:'Although I can understand complex ideas when I read them, expressing the same ideas spontaneously is still difficult for me.'},
{id:'l4-02',d:4,topic:'work',t:'One of my goals is to communicate more confidently in meetings without translating every sentence in my head first.'},
{id:'l4-03',d:4,topic:'learning',t:'A useful learning system should make progress visible while keeping the daily workload small and predictable.'},
{id:'l4-04',d:4,topic:'school',t:'When discussing a child’s progress, it helps to separate what I observed from what I am worried might happen.'},
{id:'l4-05',d:4,topic:'unige',t:'Graduate study will require me to read efficiently, summarize ideas, and respond to questions under time pressure.'},
{id:'l4-06',d:4,topic:'finance',t:'A good financial decision should consider both expected returns and the pressure created by monthly cash flow.'},
{id:'l5-01',d:5,topic:'unige',t:'If I want to succeed in graduate school, I need to develop not only academic vocabulary but also the ability to explain and defend my ideas clearly.'},
{id:'l5-02',d:5,topic:'ai',t:'Technology can make learning more efficient, but only when the tools reduce unnecessary cognitive load instead of adding more distractions.'},
{id:'l5-03',d:5,topic:'education',t:'When discussing education policy, it is useful to separate personal experience from evidence that can be generalized to a larger population.'},
{id:'l5-04',d:5,topic:'work',t:'In an interview, a concise answer is usually stronger when it includes a concrete example and a clear explanation of the result.'},
{id:'l5-05',d:5,topic:'psychology',t:'A sustainable routine should still work on difficult days, because consistency depends more on design than on motivation.'},
{id:'l5-06',d:5,topic:'unige',t:'Academic discussions often require students to compare competing explanations rather than simply repeat the information they have read.'},
{id:'l6-01',d:6,topic:'unige',t:'A strong academic argument should acknowledge reasonable counterarguments while still presenting a clear position supported by relevant evidence.'},
{id:'l6-02',d:6,topic:'unige',t:'The ability to synthesize competing perspectives is especially important when a topic involves uncertainty, trade-offs, or incomplete evidence.'},
{id:'l6-03',d:6,topic:'ai',t:'As artificial intelligence becomes more capable, workers may benefit most from developing judgment, communication, and domain expertise that complement automation.'},
{id:'l6-04',d:6,topic:'education',t:'An educational intervention can appear effective in a small study while producing different results when implemented across a larger and more diverse population.'},
{id:'l6-05',d:6,topic:'finance',t:'Long-term investment decisions should account for expected return, volatility, taxes, liquidity needs, and the investor’s ability to tolerate prolonged drawdowns.'},
{id:'l6-06',d:6,topic:'work',t:'A persuasive professional recommendation should explain the evidence, the trade-offs, and the assumptions that would change the conclusion.'}
];
